language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "gamehub";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: game-hub2019
  api_key:
<<<<<<< Updated upstream
    secure: ZfWLZz27J3sI2ZW6Gst9ee9U5HmiEkPfPn0oPKzuw96PPo1jSAEpxNFJivLMTzpuVuOM3u8ULcA3EsyDbuSuD2jIJUsUWriJINg5GkydnB+vpStjZR0VfY/Saeh1U7iQ1eDUFNinZyF5q8WqGHEqq1MwrO8Iz+bUjO0i0gHW/ugUzCKclqyA5/ZT7AYwumD+DWeeTe3SAD7YPm9lDLPF2+SanBJZfO9Clq9FBZfyJxgixYBlkZu57jA51iXhxlNpu8aCHA31rbVdNOYBZEMsCtf5dyzcEaH52Ou2GOfiKOpfJNr9+ztL4yMjePxN+eswYMJpZo39oBYaA7rR27F+5bD1XaXDb83SjJsKzYYuqfjnXlqIuaGUdICHMb0ZWpMwk0lUVYtujqwzY5MFxOJc6tmOaZkVqluBLzKShiCf0S4FPKXcp2j/IwLiVh0b6j/fRKIYEfnx4OpBihmlnutjvEerai8MGJEKwexG5uPAICHOxH2LuqTZEtyerSqm5Qj3VnlfYn0Fda2EF4NJWjYy8HZ7LxuYthZ91U3p1cp3RkUJDUQMmMOM0BIHodci/+CB2Fu1b8BYyGTEXZx7Ga1dOLjEAh39z6zXRdRrBlm4Rpho7ZP99o9KL+42v6keBaRK5LgaZuk2nbwvnxH39cR67lSfH6cY8SA7holAzUE6Eb4=
=======
    secure: o0tJPcDInhGHGMHG3WSVlGcVgLOwaoEzQjMrs/nRpXDX594Rtwmc7kCgeejeCH5cmwaiv67pjB1wK/l1jxO7b58YEOanKmjMz7ROqOBpao4D72eMYjabmMoh5dt6sP8RsFYpaOtEBxLnQ4KJMDRTWFwNulNUFklOUZjKNrw+L3V/xsSf+UXZ5AEZultVohF5YBo7UKVaIqpfYQw+ZowHjyFzj8ngoJB3vxjyPRkEScc+XsRU3ucRVLKN8xGg6oaDCKUPSCjO4Ck1d5b1/GYucuRuJBWPvEfkVujY9dqfckX/CEVs2Ai/sp0olOJq/H3E6MRwtA1gdofjiBf4jLYnu//kGQJUSwl88l1I2eCzDZEvP9CJ6szvp1/Z5e1GjKAruIDPahu8RFZ3JGyWc2Bw9IwJc3YudrfqX/dn3LoMD8Tp6p5tJjgF3PwFKfbNELk49yA8kF6U8owUduq4OteFWEYjAxgPaGIgNpq7mzqqsbMwO3G2Oi0D1NP4ozS8ImL+QwIi/6ASaRNBtZC7plO/4zrfdxrZ7DaihJcxs0Qi0uW7AxL4YO1pLlFBOONNrC01fGQr7wHC4vgLyp22kX3xx6ToxkqltJdmZT/CzmwIyZDfiss2XzuZhSUQ0GBDu3PLre7ofnZr5TMVpDf4Ihi4TScmjfIyLWxKFJ6jPEYlSeU=
>>>>>>> Stashed changes
