language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "gamehub";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: game-hub2019
  api_key:
    secure: o0tJPcDInhGHGMHG3WSVlGcVgLOwaoEzQjMrs/nRpXDX594Rtwmc7kCgeejeCH5cmwaiv67pjB1wK/l1jxO7b58YEOanKmjMz7ROqOBpao4D72eMYjabmMoh5dt6sP8RsFYpaOtEBxLnQ4KJMDRTWFwNulNUFklOUZjKNrw+L3V/xsSf+UXZ5AEZultVohF5YBo7UKVaIqpfYQw+ZowHjyFzj8ngoJB3vxjyPRkEScc+XsRU3ucRVLKN8xGg6oaDCKUPSCjO4Ck1d5b1/GYucuRuJBWPvEfkVujY9dqfckX/CEVs2Ai/sp0olOJq/H3E6MRwtA1gdofjiBf4jLYnu//kGQJUSwl88l1I2eCzDZEvP9CJ6szvp1/Z5e1GjKAruIDPahu8RFZ3JGyWc2Bw9IwJc3YudrfqX/dn3LoMD8Tp6p5tJjgF3PwFKfbNELk49yA8kF6U8owUduq4OteFWEYjAxgPaGIgNpq7mzqqsbMwO3G2Oi0D1NP4ozS8ImL+QwIi/6ASaRNBtZC7plO/4zrfdxrZ7DaihJcxs0Qi0uW7AxL4YO1pLlFBOONNrC01fGQr7wHC4vgLyp22kX3xx6ToxkqltJdmZT/CzmwIyZDfiss2XzuZhSUQ0GBDu3PLre7ofnZr5TMVpDf4Ihi4TScmjfIyLWxKFJ6jPEYlSeU=
