language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "gamehub";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: game-hub2019
  api_key:
    secure: Pqlk2lo/gAcgyV1ZnwihIXtlHz0n60fOWXLkzQFDQmYhWOfhj3AvAiM6PUZxU7Jhke7UEvTtsPkCvY7lvuJKNciEFWQ2C8jFqwfxtT4i0Ng0wDpmgC7gTFqCFa28Pabms2l7S1O6M7EAMFGuwf1bbuvq48DjiL69FKRXq+zDY7slUW0/NwTKZm4F7Yinj+7FxA+zNW5x4NlRnC3J0y4h4TTtJJWNbH/WzMtiDDJUvcBenAwOo9QztOtkJMIrer6Le6q9pPFtAAktXpGtQowKrAZRxX1qlmlkkeTCowUj3udkylWBoMUSOUS82hlt8rHB+FuZD03V9zkp2I1o7KS895ffJAe69D53sVSN1q4n2ynpn5BIw9CPk0IquDPrU7B0YM05EcWn9hwFr7Ps1tOb+BOaNB2A3jfS/GQvLQLlZNt714hfNrGEEHyj7iB5Q+pog86ffKrDxlPtWgUobB6DyjfePITWQqDXXmm8DkhD49Mv7/vYn6v1LVUGffaepGpQ10/tp71mE4ziT67m5XVgcFDwIrrnnX0T8cHHWbt/RWu/85DMjKJf/6mxVY8lKd9S79kYxQlztkvzPnQiQGZWxonedZM74Kk5eCJz8lCXkg9+LMp+0nqgRcjYW6yDVklcLUHlYpnTB9kDUSeVoredxaY3mNJQwzsUzJ8Go7YIsOo=
