language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "gamehub";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: game-hub2019
  api_key:
    secure: KheEZM/lUiyUoWsttKqGa2SKk8FCvP9QEmOK9a0bq2UmGEM04IVf5x19Ik/W2rGcBNHC16H/FDFYupGw+aBlcpITNP5UhV8ga4hlnB0yG4I9HmXHrT/omHz+DLxjkkvXva2jHOmiyXeiMYrAzBsLPvkmJHLqX4+eenQN3XBfQ7pm3wcTB75OQ6piYzVhYf8/xVpIWrVRhr7XqTe1d0PDaGIzxPp581YB1O5rJc4dL1e8UJRTWL1zf++Kr5sPdZIzSffFFTrUIqU02MRylOmMyoM96ZxMzWlqyzcppwF99sueCDYAB6Q/dyzQr3Ujj2zv/Lp9SgM2hrRfL58ML7WcNXOsecj6MbXtTztew8rd1gaQV+1U52uhf37KQzYAh/RFF/ptC9xlireG6qrD0vJLa/1rE9iVkoLPG4YkFnov4RfYQMv7qM11yd714/5UDc7VO/z/yQ99qSI2UGgK4eB3sNvyAzPoO9dpQOf2A/HrcrH/Q+2GwkbGhd3bw5Te0Jy/9kRd2Y107HtWdPUIcp1OQOFOCo/n2fyJp84NHk6kUwQrHptDN+SXWpQjEwZtrE1W1dXFuzhr0r8s/PeF5spZc6LmrcjS+WDlB/to2HxhBY/hiRCuCbsAuDC1dF9Q6U3yuIg7UbrjF/j0kdwxK4t/B32vOOFzZNW8Blabt2xc5bQ=

